services:
  - type: web
    name: order-app-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: order-app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: order-app-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: order-app-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: order-app-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: order-app-db
          property: password
      - key: CORS_ORIGIN
        value: https://order-app-ui.onrender.com

databases:
  - name: order-app-db
    databaseName: orderapp
    user: orderapp_user
